script: true
env:
  global:
    # the encrypted NEWRELIC_LICENSE_KEY
    - secure: fafOsS/qHgKjlPWjYbYSZohjEwiFFLmVt7cX2bWmI1FKDb+zJZfrrNnoa/njWZwmnOd2Vg0k+i8e/v0+trP8kkpXSkRqjCS3ednwKQ6tyArV4el9tbOiN+x1/KnQUMBQbak/qEivZcLgo9fZvSoMjLBJxoCdP6thyIMROhIAMgvvQI6d9Np6e4hYBP/p/wi4+cBAinMJln1lVsSOpEzBgR2ziQH3KjXyK9xYZ4rZaB8JwsWmW6I2saUVMM/9XhGTGBrOpWr298QIbqlO1KOV1Xqer7ka8iKXcaFMsTEO1hjQj6MBkPWFaAnoZti+/oRRWywiVGIr5tvljpNZifRnluxFREaRdUx2WzwMC7dCX8sjRLa2rbLBXzKlAWpB2RcB15UOungHDGmAiFU1+r/ZwaGil44cJ1FZNHmyHn9sI8opgxy1mCzvYbyQy5fJIvaw/ZJrkQHijOlweLCgxGUxKXV6HpLqTVWtVx/YnIKCB7vDOGA+7EWz96B1U8ddY6aI6Cj+vmnSAVQS7h568SFNnNbtGzSbzVXH6qzLID3bLibs2KgsYxmhP27YxYcHDftyeJQBNSQDdyEIt5NEv62y/Ladrw1yQ0cl24RGaXAGaziEuWn+Ku/U6iESw4a8avnHfHX6+a5a7namYVWBFqm4IuPB3bOONzlH2i7jv8RtkLQ=
    # the encrypted OPENSHIFT_PASSWORD
    - secure: ptIu5vdQ1AGreAPNt8d7KE2JPpp+tQ+Zi5zuGXlV+SGWu4gpPSDmvl8zo36R/idGr2fHP8zTph0quFzbM5Hmvw8xGIvquWvza3Q1jCATGedCNEZnCfbtNJk3lpw3J+5t+dkAHR/uIRuKquq8uS4K828uv8/mJoJFLCuwCz+gKXCe+Ju9Qqi/+qCmTlgiex7QQGC+TYbQ2bZOm2fStZgp/GyPk8rLhWfh/d1+ScP57n8c4ZPN5lRm2L6bGTp+DyIOKaefXbaHiHqYlRnF8SyuWTslInvMPbzaJGDJz+0JAQc1wZDTvWtmKiYzqwTgPHGaFnMoJARhdeXVt7VrnwEK2BcpC7e6t71Ix35+3Ct1Pe0OGju8RC4zu5h/Y8E98XGIgjumdnUBumgbjfeN2QAGG3Ox4Drj8b+iHylLZpZetISRHGD8o7UobMsJzfKPvAQx1oazXuaj+W16f4VSXAI/M9dqyz3nx63cGC/JZa3Uknct17uPdcRc3tAZpromSJhxuEntEoQ6/0cYHz8CVSNJ4AUxCSGslmBVc2qFWBkQ/yNfG9o9HQ7sBiV5QYPw3HFqB5lOLeh0PVE8l7tT6ojSfi2nFA+4cytiPFnZwrZs8PGFbCQdRFfYmQ3VlFshAxLt1gKFVQLKVCClhX0vtHXXiINKIoV9bja+9L5zcA+MWcY=
before_deploy:
  - gem install rhc
  - rhc env-set OPENSHIFT_NEWRELIC_LICENSE_KEY=$NEWRELIC_LICENSE_KEY -a circleci -l mail@tknerr.de -p $OPENSHIFT_PASSWORD
deploy:
  provider: openshift
  user: mail@tknerr.de
  password: $OPENSHIFT_PASSWORD
  app: circleci
  domain: tkn
  on:
    repo: tknerr/circleci-redirector
